services:
  data_engineering:
    build:
      context: ./stages/data_engineering
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - WORKERS=4
    volumes:
      - ./data:/app/data
      - ./stages/data_engineering:/app

  model_engineering:
    build:
      context: ./stages/model_engineering
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./stages/model_engineering:/app
      - ./data/preprocessed:/app/training_data
      - ./models:/app/models
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    labels:
      - "devcontainer.context=./stages/model_engineering"
    command: tail -f /dev/null  # This keeps the container running for testing purposes

      

  model_api:
    build:
      context: ./stages/deployment/api
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./stages/deployment/api:/app
      - ./models:/app/models
    environment:
      - PORT=8082
      - HOST=0.0.0.0
      - WORKERS=4
    ports:
      - "8082:8082"

  streamlit:
    build:
      context: ./stages/deployment/app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - model_api
    environment:
      - FASTAPI_URL=http://model_api:8082
      - PORT=8501
    volumes:
      - ./stages/deployment/app:/app
  
