services:
  data_engineering:
    build:
      context: ./stages/data_engineering
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT = 8080
      - HOST = 0.0.0.0
      - WORKERS = 4
      - MLFLOW_TRACKING_URI=http://localhost:8080
      - MLFLOW_EXPERIMENT_NAME=ml_experiment
    volumes:
      - ./data:/app/data
      
  model_engineering:
    build:
      context: ./stages/model_engineering
      dockerfile: Dockerfile
    volumes:
      - ./data/preprocessed:/app/data/training_data
    environment:
      - PORT=8081
      - MLFLOW_TRACKING_URI=http://localhost:8081
      - MLFLOW_EXPERIMENT_NAME=ml_experiment
    ports:
      - "8081:8081"
      

  # model_api:
  #   build:
  #     context: ./stages/deployment/api
  #     dockerfile: Dockerfile
  #   environment:
  #     - PORT=8082
  #     - HOST=0.0.0.0
  #     - WORKERS=4
  #   depends_on:
  #     - model_engineering

  # streamlit:
  #   build:
  #     context: ./stages/deployment/app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - model_api
  #   environment:
  #     - FASTAPI_URL=http://api:8000
  #     - PORT=8501
  
