services:
  modelAPI:
    build:
      context: ./stages/deployment/api
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - WORKERS=4
    depends_on:
      - model_engineering

  streamlit:
    build:
      context: ./stages/deployment/app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - FASTAPI_URL=http://api:8000
      - PORT=8501
  
