simple_lstm:
  lstm:
    input_size: 1
    hidden_size: 2
    num_layers: 1
  additional_features_size: 128

resnet:
  conv:
    in_channels: 1
    out_channels: 64
    kernel_size: 7
    stride: 2
    padding: 3
    bias: False
  additional_features_size: 128


crnn:
  cnn:
    conv1:
      in_channels: 1
      out_channels: 64
      kernel_size: 3
      stride: 1
      padding: 1
    pool1_kernel_size: 2
    conv2:
      in_channels: 64
      out_channels: 128
      kernel_size: 3
      stride: 1
      padding: 1
    pool2_kernel_size: 2
  lstm:
    input_size: 1
    hidden_size: 256
    num_layers: 2
  additional_features_size: 128



